export { default as soloBuildingWebsite1Svg } from "./svg/solo-building-website1.svg"
export { default as soloBuildingWebsite2Svg } from "./svg/solo-building-website2.svg"
export { default as buildingWebsiteSvg } from "./svg/building-website.svg"
export { default as soloCodingSvg } from "./svg/solo-coding.svg"
export { default as soloDesigningSvg } from "./svg/solo-designing.svg"
export { default as trioPlanningSvg } from "./svg/trio-planning.svg"
export { default as messageSentSvg } from "./svg/message-sent.svg"
export { default as teamSvg } from "./svg/team.svg"
export { default as pageNotFoundSvg } from "./svg/page-not-found.svg"
export { default as loginDoorSvg } from "./svg/login-door.svg"
export { default as bgmWaveSvg } from "./svg/bgm-wave.svg"
export { default as bgmWaveSvg2 } from "./svg/bgm-wave2.svg"
export { default as bgmWaveSvg3 } from "./svg/bgm-wave3-primary.svg"
export { default as bgmWaveSvg4 } from "./svg/bgm-wave3-light.svg"

export { default as cultureWebp1 } from "./webp/culture-pic1.webp"
export { default as cultureWebp2 } from "./webp/culture-pic2.webp"
export { default as cultureWebp3 } from "./webp/culture-pic3.webp"

export { default as contactUsHeaderImgJpg } from "./jpg/contactus-header.jpg"
