export { default as servicesHeaderImgJpg } from "./img/services-header.jpg"
export { default as codeSvg } from "./img/code.svg"
export { default as brushSvg } from "./img/brush.svg"
export { default as usergroupSvg } from "./img/usergroup.svg"

export { default as mariadbWebp } from "./img/mariadb.webp"
export { default as mysqlWebp } from "./img/mysql.webp"
export { default as nodeWebp } from "./img/node.webp"
export { default as nuxtjsWebp } from "./img/nuxtjs.webp"
export { default as phpWebp } from "./img/php.webp"
export { default as sassWebp } from "./img/sass.webp"
export { default as reactWebp } from "./img/react.webp"
export { default as vueWebp } from "./img/vue.webp"
export { default as tailwindWebp } from "./img/tailwind.png"
export { default as dockerWebp } from "./img/docker.webp"
export { default as laravelWebp } from "./img/laravel.webp"
export { default as pythonWebp } from "./img/python.webp"
